"""Curated catalog of REAL, well-known scholarship programs.

This is a maintained dataset of genuine programs with their official application
URLs and stable eligibility facts — NOT fabricated listings. Volatile fields that
change yearly (exact deadline dates, precise stipend amounts) are deliberately left
null with a "verify on official page" note rather than invented. Extend/refresh this
list, or add live source adapters, over time.
"""

from __future__ import annotations

from app.scholarships.models import Scholarship

CATALOG_UPDATED = "2026-09"

# fields tag vocabulary: all | ai | cs | data_science | engineering | electronics |
# business | finance | economics | management | medicine | law | social_sciences |
# natural_sciences | humanities | arts
_RAW: list[dict] = [
    {
        "title": "Swiss Government Excellence Scholarships",
        "provider": "Swiss Confederation (FCS)",
        "country": "Switzerland",
        "degree_levels": ["phd", "postdoc"],
        "fields": ["all"],
        "scholarship_type": "government",
        "funding_type": "fully_funded",
        "nationality_eligibility": "international",
        "language_requirements": "Language of instruction (English/German/French) proof; varies.",
        "deadline_note": "Annual — country-specific deadlines; verify on official page.",
        "description": "Research and PhD/postdoc scholarships for international scholars at Swiss universities.",
        "application_url": "https://www.sbfi.admin.ch/sbfi/en/home/education/scholarships-and-grants/swiss-government-excellence-scholarships.html",
    },
    {
        "title": "ETH Zurich Excellence Scholarship (ESOP)",
        "provider": "ETH Zurich",
        "institution": "ETH Zurich",
        "country": "Switzerland",
        "degree_levels": ["master"],
        "fields": ["all"],
        "scholarship_type": "university",
        "funding_type": "fully_funded",
        "nationality_eligibility": "international",
        "deadline_note": "Annual (with Master's admission); verify on official page.",
        "description": "Full tuition + living stipend for outstanding Master's students at ETH Zurich.",
        "application_url": "https://ethz.ch/en/studies/financial/scholarships/excellencescholarship.html",
    },
    {
        "title": "EPFL Excellence Fellowships",
        "provider": "EPFL",
        "institution": "EPFL",
        "country": "Switzerland",
        "degree_levels": ["master"],
        "fields": ["engineering", "cs", "ai", "data_science", "natural_sciences"],
        "scholarship_type": "university",
        "funding_type": "fully_funded",
        "nationality_eligibility": "international",
        "deadline_note": "Annual (with Master's admission); verify on official page.",
        "description": "Fellowships covering living costs for top Master's applicants at EPFL.",
        "application_url": "https://www.epfl.ch/education/master/master-excellence-fellowships/",
    },
    {
        "title": "DAAD Study Scholarships (Master's)",
        "provider": "DAAD",
        "country": "Germany",
        "degree_levels": ["master"],
        "fields": ["all"],
        "scholarship_type": "government",
        "funding_type": "fully_funded",
        "nationality_eligibility": "international",
        "language_requirements": "IELTS/TOEFL or German proof depending on programme.",
        "deadline_note": "Annual — varies by country/programme; verify on official page.",
        "description": "Monthly stipend + allowances for international Master's students in Germany.",
        "application_url": "https://www.daad.de/en/study-and-research-in-germany/scholarships/",
    },
    {
        "title": "DAAD Research Grants (Doctoral)",
        "provider": "DAAD",
        "country": "Germany",
        "degree_levels": ["phd"],
        "fields": ["all"],
        "scholarship_type": "research",
        "funding_type": "fully_funded",
        "nationality_eligibility": "international",
        "deadline_note": "Annual — varies by country/programme; verify on official page.",
        "description": "Doctoral research grants for international PhD candidates in Germany.",
        "application_url": "https://www.daad.de/en/study-and-research-in-germany/scholarships/",
    },
    {
        "title": "Deutschlandstipendium",
        "provider": "German Federal Government + partners",
        "country": "Germany",
        "degree_levels": ["bachelor", "master"],
        "fields": ["all"],
        "scholarship_type": "university",
        "funding_type": "partial",
        "nationality_eligibility": "international",
        "deadline_note": "Set by each university; verify on the university page.",
        "description": "€300/month merit scholarship for students at participating German universities.",
        "application_url": "https://www.deutschlandstipendium.de/",
    },
    {
        "title": "Erasmus Mundus Joint Master's (EMJM)",
        "provider": "European Commission (EACEA)",
        "country": "Europe (multi-country)",
        "countries": ["Germany", "France", "Netherlands", "Sweden", "Italy", "Belgium", "Spain"],
        "degree_levels": ["master"],
        "fields": ["all"],
        "scholarship_type": "government",
        "funding_type": "fully_funded",
        "nationality_eligibility": "international",
        "deadline_note": "Per programme — typically winter/spring; verify on the programme page.",
        "description": "Fully-funded joint Master's studied across multiple European universities.",
        "application_url": "https://erasmus-plus.ec.europa.eu/opportunities/opportunities-for-individuals/students/erasmus-mundus-joint-masters",
    },
    {
        "title": "Chevening Scholarships",
        "provider": "UK Government (FCDO)",
        "country": "United Kingdom",
        "degree_levels": ["master"],
        "fields": ["all"],
        "scholarship_type": "government",
        "funding_type": "fully_funded",
        "nationality_eligibility": "specific",
        "nationality_note": "Chevening-eligible countries (incl. India); check the country list.",
        "work_experience_requirement": "Typically ~2 years work experience.",
        "min_work_experience_years": 2,
        "deadline_note": "Annual — usually opens Aug, closes Nov; verify on official page.",
        "description": "UK Government global scholarship for a one-year Master's.",
        "application_url": "https://www.chevening.org/",
    },
    {
        "title": "Commonwealth Scholarships (UK)",
        "provider": "Commonwealth Scholarship Commission",
        "country": "United Kingdom",
        "degree_levels": ["master", "phd"],
        "fields": ["all"],
        "scholarship_type": "government",
        "funding_type": "fully_funded",
        "nationality_eligibility": "commonwealth",
        "nationality_note": "Citizens of eligible Commonwealth countries (incl. India).",
        "deadline_note": "Annual — varies by scheme; verify on official page.",
        "description": "UK-funded Master's/PhD scholarships for Commonwealth country citizens.",
        "application_url": "https://cscuk.fcdo.gov.uk/scholarships/",
    },
    {
        "title": "Gates Cambridge Scholarship",
        "provider": "University of Cambridge",
        "institution": "University of Cambridge",
        "country": "United Kingdom",
        "degree_levels": ["master", "phd"],
        "fields": ["all"],
        "scholarship_type": "university",
        "funding_type": "fully_funded",
        "nationality_eligibility": "international",
        "nationality_note": "Applicants from outside the UK.",
        "deadline_note": "Annual — aligns with Cambridge course deadlines; verify.",
        "description": "Full-cost postgraduate scholarships at the University of Cambridge.",
        "application_url": "https://www.gatescambridge.org/",
    },
    {
        "title": "Rhodes Scholarship",
        "provider": "Rhodes Trust",
        "institution": "University of Oxford",
        "country": "United Kingdom",
        "degree_levels": ["master", "phd"],
        "fields": ["all"],
        "scholarship_type": "fellowship",
        "funding_type": "fully_funded",
        "nationality_eligibility": "specific",
        "nationality_note": "Eligible constituencies/countries; check the list.",
        "deadline_note": "Annual — constituency-specific; verify on official page.",
        "description": "Postgraduate study at the University of Oxford, fully funded.",
        "application_url": "https://www.rhodeshouse.ox.ac.uk/scholarships/",
    },
    {
        "title": "Fulbright Foreign Student Program",
        "provider": "U.S. Department of State",
        "country": "United States",
        "degree_levels": ["master", "phd"],
        "fields": ["all"],
        "scholarship_type": "government",
        "funding_type": "fully_funded",
        "nationality_eligibility": "international",
        "language_requirements": "TOEFL/IELTS typically required.",
        "deadline_note": "Annual — administered by country commissions; verify locally.",
        "description": "U.S. government graduate scholarships for international students.",
        "application_url": "https://foreign.fulbrightonline.org/",
    },
    {
        "title": "Knight-Hennessy Scholars",
        "provider": "Stanford University",
        "institution": "Stanford University",
        "country": "United States",
        "degree_levels": ["master", "phd"],
        "fields": ["all"],
        "scholarship_type": "university",
        "funding_type": "fully_funded",
        "nationality_eligibility": "international",
        "deadline_note": "Annual — typically closes October; verify on official page.",
        "description": "Fully-funded graduate study across any Stanford school.",
        "application_url": "https://knight-hennessy.stanford.edu/",
    },
    {
        "title": "Vanier Canada Graduate Scholarships",
        "provider": "Government of Canada",
        "country": "Canada",
        "degree_levels": ["phd"],
        "fields": ["all"],
        "scholarship_type": "government",
        "funding_type": "fully_funded",
        "nationality_eligibility": "international",
        "deadline_note": "Annual — nominated by the university; verify on official page.",
        "description": "Doctoral scholarships (CAD 50,000/yr) at Canadian universities.",
        "application_url": "https://vanier.gc.ca/en/home-accueil.html",
    },
    {
        "title": "Australia Awards Scholarships",
        "provider": "Australian Government (DFAT)",
        "country": "Australia",
        "degree_levels": ["master", "phd"],
        "fields": ["all"],
        "scholarship_type": "government",
        "funding_type": "fully_funded",
        "nationality_eligibility": "developing",
        "nationality_note": "Citizens of participating developing countries.",
        "deadline_note": "Annual — country-specific; verify on official page.",
        "description": "Long-term development scholarships for study in Australia.",
        "application_url": "https://www.dfat.gov.au/people-to-people/australia-awards/australia-awards-scholarships",
    },
    {
        "title": "Holland Scholarship",
        "provider": "Dutch Ministry of Education + universities",
        "country": "Netherlands",
        "degree_levels": ["bachelor", "master"],
        "fields": ["all"],
        "scholarship_type": "government",
        "funding_type": "partial",
        "nationality_eligibility": "international",
        "nationality_note": "Non-EEA students.",
        "deadline_note": "Usually early in the year; verify on the university page.",
        "description": "€5,000 first-year grant for non-EEA students in the Netherlands.",
        "application_url": "https://www.studyinnl.org/finances/holland-scholarship",
    },
    {
        "title": "Swedish Institute Scholarships for Global Professionals",
        "provider": "Swedish Institute",
        "country": "Sweden",
        "degree_levels": ["master"],
        "fields": ["all"],
        "scholarship_type": "government",
        "funding_type": "fully_funded",
        "nationality_eligibility": "developing",
        "nationality_note": "Citizens of listed (mostly developing) countries.",
        "deadline_note": "Annual — typically winter; verify on official page.",
        "description": "Fully-funded Master's studies in Sweden for global professionals.",
        "application_url": "https://si.se/en/apply/scholarships/",
    },
    {
        "title": "Eiffel Excellence Scholarship Programme",
        "provider": "French Ministry for Europe & Foreign Affairs",
        "country": "France",
        "degree_levels": ["master", "phd"],
        "fields": ["engineering", "economics", "management", "law", "natural_sciences", "cs"],
        "scholarship_type": "government",
        "funding_type": "stipend",
        "nationality_eligibility": "international",
        "deadline_note": "Annual — nominated by the French institution; verify.",
        "description": "Living allowance (and some costs) for top international students in France.",
        "application_url": "https://www.campusfrance.org/en/eiffel-scholarship-program-of-excellence",
    },
    {
        "title": "MEXT Japanese Government Scholarship",
        "provider": "Government of Japan (MEXT)",
        "country": "Japan",
        "degree_levels": ["bachelor", "master", "phd"],
        "fields": ["all"],
        "scholarship_type": "government",
        "funding_type": "fully_funded",
        "nationality_eligibility": "international",
        "deadline_note": "Annual — embassy or university track; verify locally.",
        "description": "Japanese government scholarship covering tuition, stipend and travel.",
        "application_url": "https://www.studyinjapan.go.jp/en/planning/scholarship/",
    },
    {
        "title": "Global Korea Scholarship (GKS)",
        "provider": "Government of South Korea (NIIED)",
        "country": "South Korea",
        "degree_levels": ["bachelor", "master", "phd"],
        "fields": ["all"],
        "scholarship_type": "government",
        "funding_type": "fully_funded",
        "nationality_eligibility": "international",
        "deadline_note": "Annual — embassy or university track; verify locally.",
        "description": "Korean government scholarship: tuition, stipend, airfare, language training.",
        "application_url": "https://www.studyinkorea.go.kr/en/scholarship/allnew_gks.do",
    },
    {
        "title": "Singapore International Graduate Award (SINGA)",
        "provider": "A*STAR",
        "country": "Singapore",
        "degree_levels": ["phd"],
        "fields": ["engineering", "natural_sciences", "cs", "ai", "data_science", "medicine"],
        "scholarship_type": "research",
        "funding_type": "fully_funded",
        "nationality_eligibility": "international",
        "deadline_note": "Biannual intakes; verify on official page.",
        "description": "Fully-funded PhD in science/engineering at Singapore universities.",
        "application_url": "https://www.a-star.edu.sg/Scholarships/for-graduate-studies/singapore-international-graduate-award-singa",
    },
    {
        "title": "Funded PhD Research Fellowships (Norwegian universities)",
        "provider": "Norwegian universities (e.g. UiO, NTNU, UiB)",
        "country": "Norway",
        "degree_levels": ["phd"],
        "fields": ["all"],
        "scholarship_type": "research",
        "funding_type": "fully_funded",
        "nationality_eligibility": "international",
        "nationality_note": "Open internationally; PhD positions are salaried employment.",
        "opportunity_type": "funded_phd_position",
        "deadline_note": "Rolling — advertised as vacancies; check listings.",
        "description": "In Norway, PhD positions are salaried jobs advertised on the national academic portal.",
        "application_url": "https://www.jobbnorge.no/en/search?Category=PhD",
    },
    {
        "title": "Government of Ireland International Education Scholarships",
        "provider": "Higher Education Authority (HEA), Ireland",
        "country": "Ireland",
        "degree_levels": ["master", "phd"],
        "fields": ["all"],
        "scholarship_type": "government",
        "funding_type": "stipend",
        "nationality_eligibility": "international",
        "deadline_note": "Annual — typically spring; verify on official page.",
        "description": "€10,000 stipend + fee waiver for one year of study in Ireland.",
        "application_url": "https://hea.ie/funding-governance-performance/funding/student-finance/course-grant/government-of-ireland-international-education-scholarships/",
    },
    {
        "title": "Italian Government Scholarships (MAECI)",
        "provider": "Italian Ministry of Foreign Affairs (MAECI)",
        "country": "Italy",
        "degree_levels": ["master", "phd"],
        "fields": ["all"],
        "scholarship_type": "government",
        "funding_type": "partial",
        "nationality_eligibility": "international",
        "deadline_note": "Annual — usually spring; verify on official page.",
        "description": "Italian government grants for international students and researchers.",
        "application_url": "https://studyinitaly.esteri.it/en/call-for-grant",
    },
    {
        "title": "Ernst Mach Grant (OeAD)",
        "provider": "OeAD, Austria",
        "country": "Austria",
        "degree_levels": ["master", "phd"],
        "fields": ["all"],
        "scholarship_type": "government",
        "funding_type": "stipend",
        "nationality_eligibility": "international",
        "deadline_note": "Annual — varies by track; verify on official page.",
        "description": "Austrian government grants for international students and researchers.",
        "application_url": "https://oead.at/en/to-austria/grants-and-scholarships",
    },
]


def catalog() -> list[Scholarship]:
    out: list[Scholarship] = []
    for i, d in enumerate(_RAW):
        d = dict(d)
        title = d["title"]
        slug = "".join(ch if ch.isalnum() else "-" for ch in title.lower()).strip("-")
        countries = d.pop("countries", None) or [d["country"]]
        app_url = d["application_url"]
        out.append(
            Scholarship(
                id=f"sch-{i}-{slug[:40]}",
                countries=countries,
                tuition_coverage=(d.get("funding_type") in ("fully_funded", "tuition")) or None,
                source="Curated · official",
                source_url=app_url,
                scholarship_detail_url=app_url,
                official_provider_url=app_url,
                apply_direct=True,
                is_verified=False,
                sources=["Curated · official"],
                **d,
            )
        )
    return out
