apiVersion: v1
kind: Secret
metadata:
  name: agentic-secrets
  labels:
    {{- include "agentic.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $k, $v := .Values.secrets }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
